apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.soundterror.name }}
  namespace: {{ .Values.soundterror.nameSpace }}
spec:
  replicas: {{ .Values.soundterror.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.soundterror.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.soundterror.name }}
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: {{ .Values.soundterror.name }}
          image: {{ .Values.soundterror.image.repository }}:{{ .Values.soundterror.image.tag }}
          imagePullPolicy: {{ .Values.soundterror.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.soundterror.deployment.port }}

