apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.soundterror.name }}-ingress
  namespace: {{ .Values.soundterror.nameSpace }}
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/ssl-verify: "off"
spec:
  {{- if .Values.soundterror.ingress.tlsEnabled }}
  tls:
    - hosts:
        - {{ .Values.soundterror.ingress.host }}
      secretName: {{ .Values.soundterror.secrets | default .Values.soundterror.ingress.tlsSecretName }}
  {{- end }}

  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ .Values.soundterror.ingress.host }}
      http:
        paths:
          - path: /
            pathType: {{ .Values.ingress.pathType }}
            backend:
              service:
                name: {{ .Values.soundterror.name }}-service
                port:
                  number: {{ .Values.soundterror.service.port }}

