apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.soundterror.name }}-service
  namespace: {{ .Values.soundterror.nameSpace }}
spec:
  selector:
    app: {{ .Values.soundterror.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.soundterror.service.port }}
      targetPort: {{ .Values.soundterror.service.targetPort }}
      {{- if and (eq .Values.soundterror.service.type "NodePort") .Values.soundterror.service.nodePortEnabled }}
      nodePort: {{ .Values.soundterror.service.nodePort }}
      {{- end }}
  type: {{ .Values.soundterror.service.type }}

