apiVersion: v1
kind: Service
metadata:
  name: {{ include "soundterror.fullname" . }}
  labels:
    {{- include "soundterror.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "soundterror.selectorLabels" . | nindent 4 }}
  ports:
    - name: https
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}

