ingress:
  className: nginx
  pathType: ImplementationSpecific

secretstore:
  name: azure-kv
  tenantId: ""
  vaultUrl: ""

servicePrincipal:
  name: azure-sp

soundterror:
  name: soundterror
  nameSpace: soundterror
  imagePullSecretDecodingStrategy: Base64
  secrets: my-tls-secret
  tls:
    certKey: tls-crt
    keyKey: tls-key
  image:
    repository: ghcr.io/biestervictor/soundterror
    tag: main-f559898
    pullPolicy: IfNotPresent
  deployment:
    replicas: 1
    port: 8443
  service:
    type: ClusterIP
    port: 8443
    targetPort: 8443
    nodePortEnabled: false
    nodePort: 30443
  ingress:
    host: soundterror.local
    tlsEnabled: true
    tlsSecretName: my-tls-secret

